#!/bin/bash

set -e -u

cd `dirname $0`

## configuration begin
target_oses="windows darwin"
output_name="server"
## configuration end

for os in $target_oses; do

    export GOOS=$os
    export GOARCH=amd64

    if [ "$os" == "windows" ]; then
        output_file="$output_name".exe
    else
        output_file="$output_name"
    fi

    pushd cmdserver
    go build -o ../BUILD/"$GOOS"_"$GOARCH"/$output_file
    popd

done
